### ISSUE TITLE
Update code to be usable by the 0.63.1 cracked APK

### ISSUE THREAD

**Issue by Lord-Haji** [msx752/PoGoEmulator#2]

**Comment by msx752** [comment]
we have to find request url in 0.63.1 apk then rewrite to localip, it is easy in 0.35.0 (`com\nianticlabs\nia\network\NiaNet.java: 'void doSyncRequest(long object, int request_id, String url, int method, String headers, ByteBuffer body, int bodyOffset, int bodyCount)'`) but i see they removed this method where they call the request i could not find.
